mopidy:
   image: wernight/mopidy
   env_file:
    - ./config/config.mopidy
   volumes:
    - ./config/mopidy.conf:/etc/mopidy/mopidy.conf
   expose:
    - "6680:6680"

webserver:
   build: docker
   dockerfile: Dockerfile.node
   ports:
    - "12489:12489"
   links:
    - mopidy:mopidy
   volumes:
    - ./qbee:/data
   env_file:
    - ./config/config.webserver
   working_dir: /data
   command: bash -c "npm install; npm run watch"

